rules:
  - id: unsecured-embed-token
    pattern: |
      generateEmbedToken()
    message: "Embed token generation without proper validation"
    severity: WARNING
    languages: [javascript, csharp]
    metadata:
      category: security
      technology:
        - powerbi

  - id: row-level-security-bypass
    pattern-either:
      - pattern-regex: 'USERNAME\(\)\s*=\s*["\']admin["\']'
      - pattern-regex: 'USERPRINCIPALNAME\(\)\s*=\s*["\'][^"\']*["\']'
      - pattern-regex: 'USEROBJECTID\(\)\s*=\s*["\'][^"\']*["\']'
    message: "Potential RLS bypass detected in DAX expressions"
    severity: ERROR
    languages: [javascript, typescript, csharp, python, json]
