rules:
  - id: powerbi-hardcoded-creds
    pattern-regex: '(Password|Key|Token)\s*=\s*["''][^"\n]+["'']'
    message: Hardcoded credentials detected in Power BI script
    languages: [generic]
    severity: ERROR

  - id: powerbi-sqli-risk
    pattern-regex: 'Sql\.Database\(.*".*\&.*"\)|Text\.Combine\(.*,.*\)'
    message: Dynamic SQL concatenation (SQL injection risk)
    languages: [generic]
    severity: WARNING

  - id: powerbi-http-call
    pattern-regex: 'Web\.Contents\("http://"'
    message: Unencrypted HTTP call detected. Use HTTPS.
    languages: [generic]
    severity: ERROR
